# fly.toml app configuration file generated for bold-firefly-4923 on 2023-09-07T23:50:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-firefly-4923"
primary_region = "lhr"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
